### ISSUE TITLE
why can not complete super.onDestroy?

### ISSUE THREAD

**Issue by wsdjeg** [DonnieWest/VimStudio#7]
compeltion of oncreate onstop and so on is ok,just can not complete onDestroy

**Comment by wsdjeg** [comment]
hi@DonnieWest i am try your plugin ,but when i entends android'sactivity cannot complete some method such as onDestroy

**Comment by DonnieWest** [comment]
I've commented on the issue at [JavaComplete2](https://github.com/artur-shaik/vim-javacomplete2/issues/120#issuecomment-151319715)

Please do not open multiple issues across our two projects. Try to figure out where the bug is coming from and open an issue at that project. If you think someone elsewhere can help, feel free to mention them.

Please also [read here](https://wiredcraft.com/blog/how-we-write-our-github-issues/) on what makes a good issue here on Github so you can accurately convey your thoughts. A tip? The specific steps to replicate your issue is fine, but a minimal project we can `git clone` to also find your issue is fantastic.

We can continue this discussion at JavaComplete2, good luck and best wishes!

**Comment by wsdjeg** [comment]
thank you for give me the link to how to create a issue,
